### ISSUE TITLE
How to compile this project?

### ISSUE THREAD

**Issue by KevinCWKevin** [sysbiolux/JavaEncFS#1]
Hi,
    I found your project about encfs with java language. I am interesting it. But how can I use it in MacOS? And how to compile it in MacOS?

Thanks!!

**Comment by tpfau** [comment]
This is a maven project. You can compile it by simply running `mvn install ` in the folder it was cloned to.

I created a readme for the usage and also added a precompiled java executable so that it can be used directly without compilation. I hope this helps.

**Comment by KevinCWKevin** [comment]
> This is a maven project. You can compile it by simply running `mvn install ` in the folder it was cloned to.
> 
> I created a readme for the usage and also added a precompiled java executable so that it can be used directly without compilation. I hope this helps.

**Comment by KevinCWKevin** [comment]
Hi,
  Thank you first.
May I have your suggestions?  Which IDE(integrated development environment) tool you used on developing this UI in MacOS?   I am studying Encfs with Java in MacOS.  
    Thanks!!

**Comment by KevinCWKevin** [comment]
Hi,
Thank you first.
May I have your suggestions? Which IDE(integrated development environment) tool you used on developing this UI in MacOS? I am studying Encfs with Java in MacOS.
Thanks!!

**Comment by tpfau** [comment]
I used eclipse. But since the tool is just a java interface any IDE that properly supports maven should be fine.
